# This file can be used to print the flags Makefile.coq.ex pass
# Example: coqtop $(make -f Makefile.coqflags)
# Example: env COQFLAGS="$(make -f Makefile.coqflags)" ../etc/bytedump.sh bedrock2.ToCStringExprTypecheckingTest.test
.PHONY: all print_coqc
-include Makefile.coq.ex.conf
print_coqc:
	@printf "%s %s\n" "-q $(COQMF_COQLIBS)" "$(COQMF_OTHERFLAGS)"
Makefile.coq.ex.conf:
	@make -f Makefile Makefile.coq.ex 1>&2
