# autogenerated by ./etc/count2.sh
d = dict()

d["lightbulb app"] = {'importboilerplate': 105, 'workaround': 136, 'code': 176, 'spec': 301, 'bitvector': 28, 'lemma': 5, 'symex': 1278, 'loopinv': 13, 'UNTAGGED': 1686, 'doc': 3, 'proof': 20, 'unrelated': 20}

d["program logic"] = {'UNTAGGED': 1275, 'importboilerplate': 187, 'spec': 378, 'lemma': 72, 'proof': 481, 'unrelated': 87, 'workaround': 756, 'obvious': 558, 'bitvector': 366, 'test': 156, 'doc': 20, 'symex': 118, 'administrativia': 5, 'code': 142, 'lists': 26}

d["compiler"] = {'importboilerplate': 744, 'compiletimecode': 553, 'unrelated': 3246, 'administrivia': 98, 'obvious': 6159, 'test': 159, 'proof': 1281, 'library': 727, 'doc': 262, 'spec': 822, 'workaround': 64, 'notations': 9, 'bitvector': 27}

d["coqutil"] = {'UNTAGGED': 6437}

d["kami"] = {'UNTAGGED': 54227}

d["riscv-coq"] = {'importboilerplate': 358, 'unrelated': 3112, 'doc': 35, 'spec': 2166, 'obvious': 587, 'test': 112, 'proof': 118, 'workaround': 6, 'administrivia': 25, 'library': 120, 'compiletimecode': 232}

d["end-to-end"] = {'UNTAGGED': 78, 'importboilerplate': 151, 'compiletimecode': 31, 'lemma': 494, 'test': 24, 'spec': 13, 'code': 10, 'workaround': 45, 'lists': 17, 'bitvector': 190, 'maps': 17}

d["processor spec correspondence"] = {'importboilerplate': 263, 'bitvector': 2001, 'workaround': 326, 'lemma': 1758, 'automation': 241, 'lists': 55, 'maps': 36, 'UNTAGGED': 2790}
