BEDROCK_COMPILER_EXAMPLES_DIR := $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))
BEDROCK_COMPILER_EXAMPLES_VFILES := $(call rwildcard,$(BEDROCK_COMPILER_EXAMPLES_DIR),*.v)
BEDROCK_COMPILER_EXAMPLES_COQDEPFLAGS := -Q $(BEDROCK_COMPILER_EXAMPLES_DIR) $(notdir $(BEDROCK_COMPILER_EXAMPLES_DIR))
BEDROCK_COMPILER_EXAMPLES_REQUIREFLAGS := -Q $(O)/$(BEDROCK_COMPILER_EXAMPLES_DIR) $(notdir $(BEDROCK_COMPILER_EXAMPLES_DIR))

BEDROCK_COMPILER_EXAMPLES_COQFLAGS := $(COQUTIL_REQUIREFLAGS) $(BEDROCK_REQUIREFLAGS) $(BEDROCK_EXAMPLES_REQUIREFLAGS) $(RISCV_REQUIREFLAGS) $(BEDROCK_COMPILER_REQUIREFLAGS) $(BEDROCK_COMPILER_EXAMPLES_REQUIREFLAGS) -w -deprecated-from-Coq,-deprecated-since-9.0,-deprecated-since-8.20
$(O)/$(BEDROCK_COMPILER_EXAMPLES_DIR)/%.vo: private COQFLAGS += $(BEDROCK_COMPILER_EXAMPLES_COQFLAGS)
$(O)/$(BEDROCK_COMPILER_EXAMPLES_DIR)/%.vos: private COQFLAGS += $(BEDROCK_COMPILER_EXAMPLES_COQFLAGS)
$(O)/$(BEDROCK_COMPILER_EXAMPLES_DIR)/%.vok: private COQFLAGS += $(BEDROCK_COMPILER_EXAMPLES_COQFLAGS)
$(BEDROCK_COMPILER_EXAMPLES_DIR)/_CoqProject: private COQFLAGS += $(BEDROCK_COMPILER_EXAMPLES_COQFLAGS)
