BEDROCK_EXAMPLES_DIR := $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))
BEDROCK_EXAMPLES_VFILES := $(call rwildcard,$(BEDROCK_EXAMPLES_DIR),*.v)
BEDROCK_EXAMPLES_COQDEPFLAGS := -Q $(BEDROCK_EXAMPLES_DIR) $(notdir $(BEDROCK_EXAMPLES_DIR))
BEDROCK_EXAMPLES_REQUIREFLAGS := -Q $(O)/$(BEDROCK_EXAMPLES_DIR) $(notdir $(BEDROCK_EXAMPLES_DIR))

BEDROCK_EXAMPLES_COQFLAGS := $(COQUTIL_REQUIREFLAGS) $(BEDROCK_REQUIREFLAGS) $(BEDROCK_EXAMPLES_REQUIREFLAGS) -w -deprecated-from-Coq,-deprecated-since-9.0,-deprecated-since-8.20
$(O)/$(BEDROCK_EXAMPLES_DIR)/%.vo: private COQFLAGS += $(BEDROCK_EXAMPLES_COQFLAGS)
$(O)/$(BEDROCK_EXAMPLES_DIR)/%.vos: private COQFLAGS += $(BEDROCK_EXAMPLES_COQFLAGS)
$(O)/$(BEDROCK_EXAMPLES_DIR)/%.vok: private COQFLAGS += $(BEDROCK_EXAMPLES_COQFLAGS)
$(BEDROCK_EXAMPLES_DIR)/_CoqProject: private COQFLAGS += $(BEDROCK_EXAMPLES_COQFLAGS)
