BEDROCK_COMPILER_DIR := $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))
BEDROCK_COMPILER_VFILES := $(call rwildcard,$(BEDROCK_COMPILER_DIR),*.v)
BEDROCK_COMPILER_COQDEPFLAGS := -Q $(BEDROCK_COMPILER_DIR) $(notdir $(BEDROCK_COMPILER_DIR))
BEDROCK_COMPILER_REQUIREFLAGS := -Q $(O)/$(BEDROCK_COMPILER_DIR) $(notdir $(BEDROCK_COMPILER_DIR))

BEDROCK_COMPILER_COQFLAGS := $(COQUTIL_REQUIREFLAGS) $(BEDROCK_REQUIREFLAGS) $(RISCV_REQUIREFLAGS) $(BEDROCK_COMPILER_REQUIREFLAGS) -w -deprecated-from-Coq,-deprecated-since-9.0,-deprecated-since-8.20
$(O)/$(BEDROCK_COMPILER_DIR)/%.vo: private COQFLAGS += $(BEDROCK_COMPILER_COQFLAGS)
$(O)/$(BEDROCK_COMPILER_DIR)/%.vos: private COQFLAGS += $(BEDROCK_COMPILER_COQFLAGS)
$(O)/$(BEDROCK_COMPILER_DIR)/%.vok: private COQFLAGS += $(BEDROCK_COMPILER_COQFLAGS)
$(BEDROCK_COMPILER_DIR)/_CoqProject: private COQFLAGS += $(BEDROCK_COMPILER_COQFLAGS)
